#!/usr/bin/env bash

check_domain() {
    SUBDOMAINS='www lb-01 web-01 web-02'
    if [ -z "$1" ]; then
        exit 1
    fi
    if [ -z "$2" ]; then
        for subdomain in $SUBDOMAINS; do
            dig "$subdomain.$1" | awk -v subdomain="$subdomain" \
                '/^;; ANSWER SECTION:$/ { getline ; getline ; printf "The subdomain %s is a %s record and points to %s\n", subdomain, $3, $5 }'
        done
    else
        dig "$2.$1" | awk -v subdomain="$2" \
            '/^;; ANSWER SECTION:$/ { getline ; getline ; printf "The subdomain %s is a %s record and points to %s\n", subdomain, $3, $5 }'
    fi
}

check_domain "$1" "$2"
