#!/usr/bin/env bash

# Ensure that Nginx is installed and listening on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen\s*80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
